In [4]:
import numpy as np

A = 10*np.random.rand(3,4)
print(A)

[[ 5.59255106  7.00149651  7.89417606  9.8194837 ]
 [ 5.05836022  5.35172118  7.08968514  1.82333803]
 [ 8.10677676  1.55415181  6.43266161  3.59731016]]


In [9]:
cal = A.sum(axis=0)
print(cal)

[ 18.75768804  13.9073695   21.41652281  15.24013189]


In [22]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[ 29.81471408  50.34378724  36.86021364  64.43175012]
 [ 26.96686398  38.48118926  33.10381054  11.96405678]
 [ 43.21842194  11.1750235   30.03597582  23.6041931 ]]
