In [11]:
import numpy as np

a = np.random.rand(5,1)
print (a)
print (a.shape)

[[ 0.60389225]
 [ 0.6429397 ]
 [ 0.35553732]
 [ 0.11588369]
 [ 0.44658051]]
(5, 1)


In [12]:
print (a.T)

[[ 0.60389225  0.6429397   0.35553732  0.11588369  0.44658051]]


In [13]:
print(np.dot(a,a.T))

[[ 0.36468585  0.3882663   0.21470623  0.06998126  0.26968651]
 [ 0.3882663   0.41337146  0.22858906  0.07450623  0.28712434]
 [ 0.21470623  0.22858906  0.12640679  0.04120098  0.15877604]
 [ 0.06998126  0.07450623  0.04120098  0.01342903  0.0517514 ]
 [ 0.26968651  0.28712434  0.15877604  0.0517514   0.19943415]]


In [6]:
import math
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    s = 1/(1+math.exp(-x))

    
    return s

In [7]:
basic_sigmoid(5)

0.9933071490757153